version: '3.8'

services:

  nextcloud-db:
    image: mysql:latest
    container_name: nextcloud-db 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your-root-password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: your-user-password
    volumes:
      - ./db:/var/lib/mysql
    networks: 
      - nextcloud-network

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: always
    networks:
      - nextcloud-network

  # nextcloud instance 1
  nextcloud_app1:
    image: nextcloud:latest
    container_name: nextcloud_app1
    restart: always
    depends_on:
      - nextcloud-db

    ports:
      - "8080:80"
    volumes:
      - ./data:/var/www/html/data
      - ./conf1:/var/www/html/config
      - ./application1:/var/www/html/custom_apps
    environment:
      - REDIS_HOST=redis
    networks:
      - nextcloud-network

  # nextcloud instance 2
  nextcloud_app2:
    image: nextcloud:latest
    container_name: nextcloud_app2
    restart: always
    depends_on:
      - nextcloud-db
    ports:
      - "8081:80"
    volumes:
      - ./data:/var/www/html/data
      - ./conf2:/var/www/html/config
      - ./application2:/var/www/html/custom_apps
    environment:
      - REDIS_HOST=redis
    networks:
      - nextcloud-network

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/
    command: -f /mnt/locustfile.py --host http://nextcloud_nginx:80 --users 30 --spawn-rate 5 -t 4m30s
    networks:
      - nextcloud-network

  nginx:
      image: nginx:latest
      container_name: nextcloud_nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - nextcloud_app1
        - nextcloud_app2
      networks:
        - nextcloud-network

networks:
  nextcloud-network:
    driver: bridge